### ISSUE TITLE
[1.20.1] Crash with latest Let's Do API v1.2.8

### ISSUE THREAD

**Issue by MokahTGS** [Cristelknight999/DoAPI#10]
Getting a crash when updating doAPI to 1.2.8 in 1.20.1

https://pastebin.com/hBNTAFMK

**Comment by aAndrew3030** [comment]
I am having the same issue, seems to be a conflict with a mod, but I have been unable to figure out what mod it is conflicting with

**Comment by Cristelknight999** [comment]
i think this got fixed and re-uploaded as the same version. try downloading the mod again

**Comment by aAndrew3030** [comment]
The re-upload fixed the issue. In the future, best to increase the version number to avoid confusion
