### ISSUE TITLE
[BUG] Log Spam

### ISSUE THREAD

**Issue by Fyoncle** [Cristelknight999/DoAPI#28]
### What mod appears to be problematic?

 API

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

https://github.com/satisfyu/Let-s-Do-Hub/issues/58

### Steps To Reproduce

1. Open a debug world
2. See the console after API block spams it when you load the chunks

### Relevant log output

```shell
https://mclo.gs/Fc0aUCg
```

### What modloader are you running the mod on?

Fabric

**Comment by Cristelknight** [comment]
This happens if the block isn‘t placed by a player and therefore has missing data. Don‘t know if this really needs a fix

**Comment by Fyoncle** [comment]
> This happens if the block isn‘t placed by a player and therefore has missing data. DOn‘t know if this really needs a fix

Saying no one will see it and not fixing it is not kinda a good idea in my opinion, bug is a bug

**Comment by Cristelknight** [comment]
I just meant it is not a bug. Just more or less debug. The block won‘t even render correctly in this state. But I can delete it if you want

**Comment by Fyoncle** [comment]
> I just meant it is not a bug. Just more or less debug. The block won‘t even render correctly in this state. But I can delete it if you want

Delete what?

**Comment by Cristelknight** [comment]
The debug error. Or maybe just make it less frequent. What do you think?

**Comment by Fyoncle** [comment]
> Collaborator

It would be great if it completely fixed, i use debug world sometimes to test some things and it really lags me.

**Comment by Cristelknight** [comment]
Or maybe just log it as debug and less frequent? Completely removing it feels a bit weird

**Comment by Fyoncle** [comment]
> Collaborator

If it has no effect on mod or any feature, whats the reason to keep a glitchy block that doesn't even render correctly

**Comment by Cristelknight** [comment]
It‘s not about the block. The block is working fine…
I‘ll change it. But idk if this will get backlogged.

**Comment by Fyoncle** [comment]
> It‘s not about the block. The block is working fine… I‘ll change it. But idk if this will get backlogged.

Wdym by backlogged?

**Comment by Cristelknight** [comment]
Autocorrection. So annoying. I meant backported.

**Comment by Fyoncle** [comment]
> Autocorrection. So annoying. I meant backported.

Oh... :(

**Comment by Cristelknight** [comment]
On which mc version are you on?

**Comment by Fyoncle** [comment]
> On which mc version are you on?

1.20.1 Fabric
