### ISSUE TITLE
Don't work for modpack atm 8

### ISSUE THREAD

**Issue by Vodee34** [Cristelknight999/DoAPI#3]
[25juil.2023 03:41:20.526] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'doapi', Requested by: 'vinery', Expected range: '[1.1.0,)', Actual version: '[MISSING]'

lestdo api is nevertheless present in the file when I just launch jei, let'do api, let'sdo vinery and architecture the mod works well but with atm8 nothing at all

the server does not crash but no access to the book or the recipe via the jei for wine crafts

if you find a solution to that I am a taker thank you

**Comment by Cristelknight999** [comment]
I don’t understand what your problem is.

**Comment by Cristelknight999** [comment]
I don’t understand what your problem is.
