### ISSUE TITLE
Crash On Launch Sometimes

### ISSUE THREAD

**Issue by lanwoodall423** [Cristelknight999/DoAPI#32]
### What mod appears to be problematic?

🍷 Vinery

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

Minecraft crashes on startup around ~3/4 attempts referencing Let's Do mods but will launch and work flawlessly ~1/4. I've never encountered an issue like this.

The crash will report that Vinery, Applewood, and/or one or two other Let's Do mods (and only Let's Do mods) have failed to load due to index out of bounds (negative value). The mods that are reported are inconsistent i.e. it may be only vinery one time, the very next launch it may be three of them, and then on the next launch everything works fine.

Again only Let's Do mods are reported with the mods failed to load, Index out of bounds error, reporting a negative value for the index.

### Expected Behavior

Launch

### Steps To Reproduce

Install mods
Launch

### Relevant log output

```shell
crash - https://pastebin.com/ULnNggrv
latest - https://pastebin.com/8t8y4ekq
```

### What modloader are you running the mod on?

Forge

**Comment by Cristelknight** [comment]
Should be fixed for all official let‘s do mods. Applewood probably not.
