### ISSUE TITLE
game failed to start

### ISSUE THREAD

**Issue by Rogenar** [Cristelknight999/DoAPI#5]
[latest.log](https://github.com/Cristelknight999/DoAPI/files/12321430/latest.log)
![ss1](https://github.com/Cristelknight999/DoAPI/assets/122460325/5a62751b-9f96-4733-9431-d6f157bab4e9)
versiyon: API - 1.2.6b - FABRIC - 1.20.x

**Comment by jmbarnez** [comment]
I get the same issue
