### ISSUE TITLE
Still running into portlib error with new version 

### ISSUE THREAD

**Issue by francerobin** [Cristelknight999/DoAPI#6]
[latest.log](https://github.com/Cristelknight999/DoAPI/files/12326561/latest.log)

**Comment by Cristelknight999** [comment]
I see no do api related errors in that log (maybe because I read this on a phone). And yes, when loading a world you will get errors, which shouldn't do much. That is why I said it is "fixed" and not fixed. It stops crashing, that's it.

**Comment by TenKotowsky** [comment]
Hey, I'm getting a 'porting_lib_base' crash, which I guess is related to this issue. The game crashes when I try to launch it. Here's the crash log:
https://gist.github.com/TenKotowsky/b3386cec6b54a3cc711df153413fdc84

**Comment by Cristelknight999** [comment]
You don't have the newest version of doapi. It's 1.2.7, not 1.2.6

**Comment by TenKotowsky** [comment]
is it avaiable on curseforge?
![image](https://github.com/Cristelknight999/DoAPI/assets/100159503/63eba997-acb8-466d-b622-8a2a83074926)

**Comment by Cristelknight999** [comment]
There should be now a new version
