### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Roby1164** [Cristelknight999/DoAPI#7]
Upgrading to the latest release 1.2.7, there are errors in the log, see picture, there are various lines like this, with the previous version, no such problem.
![Screenshot_2](https://github.com/Cristelknight999/DoAPI/assets/24955554/d5ce4d1f-d940-4871-a966-12926a9025a8)

**Comment by Cristelknight999** [comment]
I reworked the conditional recipes, so that they work with porting lib. There should be a meadow release with the updated recipes sometime today.
